### PR TITLE
Update Strided dep to v2

### PR DESCRIPTION
**Pull request by kool7d**
Required for update of TensorCast.jl

### CODE REVIEW

**Comment by mcabbott** [comment]
Thanks I hadn't seen v2. Description here https://github.com/Jutho/Strided.jl#whats-new but I forgot what details this package does & doesn't depend on... see what tests say.

**Comment by mcabbott** [comment]
Ok it looks like we need to remove `UnsafeStridedView` completely, here:

https://github.com/search?q=repo%3Amcabbott%2FTransmuteDims.jl%20UnsafeStridedView&type=code

Probably simplest to completely drop support for Strided v1 -- anyone using that will then get the old version of this package, for now.

**Comment by kool7d** [comment]
There are some other updated compats that look ok with the tests. I tried changing the `UnsafeStridedView` and updating `Strided` to v2 but couldn't get some of the `transpose` and permutedims tests to work.

**Comment by tomsmierz** [comment]
This update is required to move CUDA.jl to version 5 and be compatible with new versions of TensorOperations.jl, which have fixed requirements of Strided to version 2.0.4.

**Comment by mcabbott** [comment]
Yes. But I think code changes are needed, not just changes to version bounds.

**Comment by tomsmierz** [comment]
Do you think it can be done? If so, in what timeframe?

**Comment by mcabbott** [comment]
I am sure it can be done, it might even be quite simple. I just haven't had the time to look, sorry, a bit over-committed.

It's possible that what needs to change may be really obvious to the authors of Strided changes, and that they may have time to look, but I haven't asked.

**Comment by tomsmierz** [comment]
Where exactly lies the problem?

**Comment by mcabbott** [comment]
If I remember right, the StridedView type used in https://github.com/mcabbott/TransmuteDims.jl/blob/master/src/strided.jl has changed.

**Comment by kmp5VT** [comment]
@mcabbott any updates on this PR?

**Comment by mcabbott** [comment]
Replaced by #43

**Pull request closed without merging**
